<!-- Fixed navbar -->
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="<?php echo $this->baseUrl(); ?>">Bootstrap theme</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
        <?php 
            $partial = array('partials/menu.phtml', 'default');
            echo $this->navigation()->menu()
                    ->setMinDepth(0)
                    ->setMaxDepth(0)
                    ->setPartial($partial)
                    ->render(); 
        ?>
    </div><!--/.nav-collapse -->
  </div>
</nav>