<?php

$htmlMenu = '<ul class="nav navbar-nav">';

foreach ( $this->container as $page ) {
    $liClass = '';
    if ( $page->getActive() ) {
        $liClass = ' class="active"';
    }
    
    $itensMenu = <<<EOF
        <li{$liClass}>
            <a href="{$page->getHref()}">
                {$page->getLabel()}
            </a>
        </li>
EOF;
    
    if ( $page->hasPages() ) {
        $arrSecondeLevel = array();
        foreach ( $page->getPages() as $key => $secondeLevel ) {
            $arrSecondeLevel[$key] = <<<EOF
                <li><a href="{$secondeLevel->getHref()}">{$secondeLevel->getLabel()}</a></li>
EOF;
            if ( $secondeLevel->get('class') === 'divider' ) {
                $arrSecondeLevel[$key] = '<li role="separator" class="divider"></li>';
            }
            if ( $secondeLevel->get('class') === 'dropdown-header' ) {
                $arrSecondeLevel[$key] = "<li class=\"dropdown-header\">{$secondeLevel->getLabel()}</li>";
            }
        }
        $strItens = implode(PHP_EOL, $arrSecondeLevel);
        $itensMenu = <<<EOF
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                    {$page->getLabel()} <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                    {$strItens}
                </ul>
            </li>
EOF;
    }
    
    $htmlMenu .= $itensMenu;
}

$htmlMenu .= '</ul>';

echo $htmlMenu;